### ISSUE TITLE
Weird right padding on the widget

### ISSUE THREAD

**Issue by hendricha** [zayronxio/Chaac-Complete-Weather#1]
Hi!

This seemed to affect minimal chaac weather widget too for me on plasma 6. It happens with both Breeze Dark and my choice of plasma theme too. 

I'm currently using Fedora Knoite 40.

If you need anything more for debug, ask away.

Absolutely not a dealbraker, since ATM I think this is the only "normal" working minimal weather widget for plasma 6 panels, that can show both temperature and weather icon. But if you could look into it maybe, that would be appreciated. 

Thank you.

[screenshot](https://github.com/user-attachments/assets/3837fd10-ce52-45bd-b28e-49eee51f8b19)

**Comment by zayronxio** [comment]
What language are you using on your system?

**Comment by hendricha** [comment]
Hungarian. ... So I guess the padding thing is related to the "Language not supported" message? :D

**Comment by zayronxio** [comment]
It's probably, I haven't had time to check, be patient, I'll fix it

**Comment by zayronxio** [comment]
What distribution are you using?

**Comment by hendricha** [comment]
Fedora 40 kinoite.

**Comment by zayronxio** [comment]
It seems that I have found the solution, this Sunday I will release the update as well as some new additions, Of note, chaac minimal now has its own repository

**Comment by zayronxio** [comment]
The improvement has already been implemented; however, the update in the KDE store is scheduled for August 1st.

If you want to test it beforehand, the minimum version already includes the improvements.
