### ISSUE TITLE
Weather/Temperature not updating

### ISSUE THREAD

**Issue by Sarcasthik** [zayronxio/Chaac-Complete-Weather#2]
Hello !
I decided to try out your widget today and I like it but it does not seem to auto-update in the taskbar nor do I see a setting so I can adjust the time between updates. 
![image](https://github.com/user-attachments/assets/89fa2228-c9f3-4ae0-b822-623ce3bbd420)

I use the Latitude/Longitude parameters rather than IP if that is anything important.
Any ideas ? Thanks for you work.

**Comment by zayronxio** [comment]
The default update time is every 15 minutes, however I will add the option to change it,

**Comment by Sarcasthik** [comment]
Great news, thanks ! 
However it still does not update on my end, is there anything I can do to check why it does not ?
It also seems it won't save my location parameters, when I booted today it shows 0°C and blank fields for Latitude/Longitude

**Comment by zayronxio** [comment]
Test now

**Comment by Sarcasthik** [comment]
It works like a charm now, thanks !
